CREATE TABLE public.bookmark (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  content_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookmark_user_content_unique UNIQUE (user_id, content_id),
  CONSTRAINT bookmarks_user_fk FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT bookmarks_landmark_fk FOREIGN KEY (content_id) REFERENCES public.landmark(contentid) ON DELETE CASCADE
);

-- Enable Row Level Security
ALTER TABLE public.bookmark ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view own bookmarks" 
  ON public.bookmark FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own bookmarks" 
  ON public.bookmark FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own bookmarks" 
  ON public.bookmark FOR DELETE 
  USING (auth.uid() = user_id);